### ISSUE TITLE
Intérieur sport ?

### ISSUE THREAD

**Issue by RomainBoulay** [benasse/canal-flask#1]
Bonjour,

D'abord, merci d'avoir ouvert ton code publiquement.
De mon côté je serais intéressé par les "Intérieur sport" (canal plus), mais malgré quelques recherches, je n'ai vu d'accessible. Saurais-tu comment accéder aux vidéos de cette émission ?

Merci !

**Comment by benasse** [comment]
Hello,
Tu peux regarder les vidéos ici : http://www.canalplus.fr/c-sport/pid2708-c-interieur-sport.html
Pour créer le flux rss, il faut trouver l'ID de l'émission dans la REST API de canal.

**Comment by RomainBoulay** [comment]
Je crois que c'est l'ID 1427 pour ce programme. As-tu le flux associé ?

**Comment by benasse** [comment]
L'ID du flux de la saison 9 semble plutôt être le 177.
J'ai rajouté le flux associé : https://github.com/benasse/canal-flask/commit/5811def4264c59f6e7f80567492828a43fa677d4 et l'ai nommé : int-sport-s9.atom

En plus j'ai rajouté un petit script qui permet de chercher l'ID le l’émission à partir du nom : https://github.com/benasse/canal-flask/commit/0dc9e024c2a59e377f164d3d132b1d651dc6176c

**Comment by RomainBoulay** [comment]
Merci bcp pour ton aide :+1:
